### ISSUE TITLE
webmail Sent folder should show To instead of From

### ISSUE THREAD

**Issue by mattfbacon** [mjl-/mox#104]
The From is likely to be the user themself so it would be more useful to show the recipient instead.

**Comment by mjl-** [comment]
indeed this makes sense, i've had similar thoughts before. i decided to implement it as suggested: showing recipients instead of sender for messages in the Sent mailbox. and at the same time showing all correspondents for collapsed threads. however, that lead to some non-intuitive behaviour: for threads, all messages would show the other side of the conversation, never the sender.
i now made a change so the from address is still shown as before, but for messages in the designated Sent mailbox, the addressees are also shown, in italic.
the addresses-column is getting a bit crowded now, may need some more whitespace...

**Comment by mattfbacon** [comment]
OK
