### ISSUE TITLE
Incorrect rua email address for Host TLSRPT

### ISSUE THREAD

**Issue by lmeunier** [mjl-/mox#125]
Mox version :
```
# mox version
0.0.9
go1.21.6 linux/arm64
```

Mox config files are initialized with this command :
```
# mox quickstart -existing-webserver -hostname ftth4.example.com admin@infra.example.com
```

In the "DNS records to add" section, I was asked to add to following DNS record:
```
; Request reporting about success/failures of TLS connections to (MX) host, for DANE.
_smtp._tls.ftth4.example.com.                 TXT "v=TLSRPTv1; rua=mailto:tls-reports@ftth4.example.com"
```

Shouldn't the rua email address be tls-reports@infra.example.com instead of tls-reports@ftth4.example.com ? As there is no `MX` record for `ftth4.example.com` and the domain `ftth4.example.com` is not listed in the domains managed by mox, emails sent to tls-reports@ftth4.example.com will always be rejected.

**Comment by mjl-** [comment]
The default config enables a "host tlsrpt" setting to accept TLS reports aimed at the host. See https://www.xmox.nl/config/#cfg-mox-conf-HostTLSRPT

While implementing TLS reporting, it confused me quite a bit. TLS reporting is written with/for MTA-STS. MTA-STS protects  recipient domains. TLS reporting can also report on DANE TLS connectivity. DANE protects MX hosts. So I went down the rabbit hole of "TLS reporting for hosts"... Also see https://mailarchive.ietf.org/arch/msg/uta/F7m4BAnILJB6HmmAPs6rAtvcD-w/

In general, TLS reporting for MX hosts can be useful, regardless of the question of recipient domain vs MX host: Email to postmaster@<yourmxhost> will be delivered with TLS too, and reporting on it can be useful.

So I'm not so sure my implementation of TLS reports towards MX hosts about recipient domains is a great idea, the generated configuration is intentional, and mox should be accepting reports sent to that address.
