### ISSUE TITLE
How to switch to "existing-webserver" from the ordinary one?

### ISSUE THREAD

**Issue by naddika** [mjl-/mox#137]
I initially set up my instance without  `-existing-webserver`. And now I need to add or switch to this option. How will I do this properly? What's described in the documentation won't work, will it? Because there it assumes that  `-existing-webserver` to be used **from the beginning**.

And I can't use the built-in webserver of Mox, I have to use my own `nginx` instance as well as  LetsEncrypt certificates.

**Comment by mjl-** [comment]
You could try this: Run the quickstart in a new/temporary directory with the -existing-webserver flag. That will generate new configuration files. Then diff the two, and apply the changes from the new file to your existing config file.

I did this just now locally. Two quickstart invocations, one without and one with -existing-webserver. Summary of the differences:
- ACME config removed.
- On the "internal" listener, AccountHTTP, AdminHTTP and WebmailHTTP get `Port: 1080` and have `Forwarded: true` (you'll have to add a forward in nginx).
- Items moved from the "public" to "internal" listener: AutoconfigHTTPS, MTASTSHTTPS, WebserverHTTP. With `Port: 81` and `NonTLS: true`. You'll have to configure forwards in nginx.
- In "public" listener, no more `HostPrivateKeyFiles` (in case you had those, with the latest version of mox). And the addition of `KeyCerts`, which you'll have to fill in with the TLS cert & key of the host, for SMTP/IMAP. Also no more `WebserverHTTPS`, nginx will be doing HTTPS.

Was there anything in particular missing/wrong with the mox webserver that nginx is needed? It's good to know what people run into, maybe I can add missing functionality to the mox webserver in the future.

**Comment by mjl-** [comment]
> Run the quickstart in a new/temporary directory with the -existing-webserver flag

Have you tried this previous suggestion? Or is there a reason you can't run the quickstart elsewhere?

> I run https websites on the same machine. Therefore, the 443 port is already occupied by nginx.

Is there a reason you cannot use the mox webserver? It does https too, and automated TLS cert management with ACME.

**Comment by mjl-** [comment]
> Do you suggest that I replace nginx ...

Well, I asked why it wasn't an option. And you said you need to run https websites. So I responded that mox can do that too. (:  I was also triggered because as far as I know the open source nginx doesn't do automatic TLS cert management with ACME (but my info is likely outdated). I assumed you weren't running big websites on that machine because you initially ran the quickstart without the existing-webserver option on that machine and wanted to keep that config, so I thought it had run OK at some point. Anyway, I do understand why you would rather run long-time proven software, no worries.
