### ISSUE TITLE
Add a fly.op deployment yaml

### ISSUE THREAD

**Issue by gedw99** [mjl-/mox#14]
It will help to make it easy to deploy .

gere is a blog article showing the god and bad of fly.io.

It would cost nothing for users m.

mit might also make it easy to do HA..

https://benhoyt.com/writings/flyio/

**Comment by mjl-** [comment]
Thanks, this was a good reason for me to finally try out fly.io, I tried setting up mox on fly.io just now.
I haven't succeeded.

What I did:
- Allocate a (paid) dedicated static IPv4 address. This is needed for sending email, due to reputation. Apps already come with a dedicated static IPv6 address by default.
- Create a volume.
- Run quickstart locally, modify configuration file. I had to try starting the app once to get the IP address and chance to add a dedicated ipv4. Then take that address to update the config. Ideally you would allocate fly resources first. Then run quickstart and adjust the config files.
- Try to figure out how to get files to a volume. I haven't succeeded. I'm seeing some docs about starting the app and sftp'ing to it, but that won't work because the app doesn't start with the config files in the volume. I didn't find a "fly volume cp" command, and nothing in their web interface. Am I supposed to launch a separate app to add a file to a volume? I did try starting the app, that all goes well, but mox quits without the config file.

Despite the config file issue, I don't think running on fly.io is going to work. At least not for sending email. Receiving email probably will work. For outgoing email, mox would have to send it through an external email submission service. Mox cannot do that yet, and it's not great to begin with. The reasons it won't work:

- fly.io doesn't set reverse DNS records for your IPs (which many mail servers will check before accepting your email). See https://community.fly.io/t/ip-reverse-dns/3459/6
- Outgoing connections don't come from your static IP (perhaps because of anycast?). This will also cause other mail servers to not accept the email you're trying to send from a fly.io app. See https://community.fly.io/t/static-egress-ip/8417

And it could very well be that fly.io blocks outgoing SMTP connections as a spam prevention measure. But I didn't get to that.

For reference, I used this fly.toml:

```
app = "mox"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "docker.io/moxmail/mox:v0.0.2-0.20230303234902-15e262b0431d-go1.20.1-alpine3.17.2"

[env]

[mounts]
  destination = "/mox"
  source = "mox"

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []
```

Perhaps the info I found is outdated, or you would like to give it a try?

**Comment by gedw99** [comment]
Hey @mjl- 

thanks for going through the attempt .

i jumped the gun and should have realised their anycast setup would make it hard.

**Comment by gedw99** [comment]
Also do you have a list of known to work clouds ? Would be good to compare the setups

**Comment by gedw99** [comment]
https://community.fly.io/t/allow-mailserver-ports/3215/4 Indicates they are not opposed to it 

matbe reach out to Kurt to see latest . I know me is pretty responsive to open source needs

**Comment by mjl-** [comment]
I don't think this can happen anytime soon due to fly limitations. So closing it now. If the situation at fly.io changes, we can reopen.
