### ISSUE TITLE
What's the default domain in an account for? 

### ISSUE THREAD

**Issue by tabatinga0xffff** [mjl-/mox#142]
What's it for?

And how to update or change one, when there're multiple ones in an account? I haven't found any property in neither the mox.conf, nor in domains.conf, nor in the UI

Regarding "catchall" -- is the default domain the one that'll receive  "catchall" incoming emails for an account and thus for all  "catchall" domains in it?  Or will  "catchall" incoming emails be delivered or forwarded **only the corresponing domain** and none other?

**Comment by mjl-** [comment]
hi @tabatinga0xffff, this corresponds to the "Domain" in an "Account", see https://www.xmox.nl/config/#cfg-domains-conf-Accounts-x-Domain.
It is marked deprecated: It used to be combined with the configured addresses for an account in Destinations: If there was no "@", the destination would be only a "localpart", and would be combined with the default domain when parsing the config to form the full address. Since quite some releases such destinations are full addresses. However, mox doesn't automatically rewrite the config, and removing this field may break some configs (unlikely, but possible), so I haven't removed it yet.

The default domain also still has some use. It is selected as domain when you're adding a new address to an account, see screenshot. The default domain is set for an account when is created, it is set to the domain name of the email address that the account is created with.

![mox-default-domain](https://github.com/mjl-/mox/assets/1684740/7cf756ab-d54c-4128-a13f-2105e7eb73e6)

I'll remove the mention of the default domain. It's too prominent, you can't currently edit it through the admin interface. It seems fine to just leave it as the domain the account was initially created with.
