### ISSUE TITLE
Allow to specify DNS listener port

### ISSUE THREAD

**Issue by Bloomers7577** [mjl-/mox#147]
I'm running pihole and unbound on the same  machine as mox and it would be great if I could specify the dns server port

**Comment by mjl-** [comment]
I don't think it's very common for software to configure a port for a DNS server. And not even per-application DNS servers. It's just in /etc/resolv.conf. So I don't think we should make DNS servers configurable for mox.

Can you add instead a separate IP address to the machine, and run unbound on that IP, and configure /etc/resolv.conf to use that resolver? That's what I do on machines with multiple DNS servers. I think pihole is often used for adblocking on browsers? So presumbly the rpi (assuming it is one) that runs pi-hole doesn't need to use that resolver? Otherwise, it may be possible to setup mox in a namespace so it sees a different /etc/resolv.conf from the rest of the system.

**Comment by mjl-** [comment]
closing issue since i don't think we can accommodate for this in mox, and seems better solved outside it. feel free to reopen if there are new options/insights.
