### ISSUE TITLE
Feature request: Allow login by just username, instead of email address

### ISSUE THREAD

**Issue by naturalethic** [mjl-/mox#18]
The local name on the default domain should be enough to sign in.

**Comment by mjl-** [comment]
Thanks, we could use some improvements to email addresses vs accounts. It's probably not immediately clear when you have to use the full email address, and when you can use the account name. Perhaps even counter-intuitive. And the terminology isn't too clear either. You're using the term "username", and "local name on the default domain".

In my mind, the account name is a short name for an account, independent of its (multiple) email addresses, that is used in the UI, and is used in the file system to store account data (including email messages). For the initial user created with the quickstart, the account name is the same as the localpart of the address specified. But for other accounts this doesn't have to be the case. And accounts can have the same localparts, but for different domains. So if anything, I would think we could allow logging in through the account name. But I don't know if that is worth the trouble and/or a good idea. I'm not generally in favor of allowing multiple ways to do a single thing. And I've been thinking about making it possible to set a password for an individual email address in an account, for sending only. So the "login by email address" seems a better fit.

Are you requesting this feature because of a specific need? Or mostly because it isn't clear you had to login by email address? Perhaps we can fix that with documentation?

**Comment by naturalethic** [comment]
I messed around with user accounts a bit and I think I understand what 'default domain' is supposed to do.  It appears to simply allow you to specify only a localname for an account, that is then automatically combined with their default domain.

I initially assumed that the local name for a user would automatically apply them to all domains (as this is how my previous mail setup did this).  Sort of like a username@*.  It would be clearer to me I think, if default domain was dropped and each email address had to be specified explicitely, while maybe adding in wildcard notation if desired.

Some wildcards possibilities:
- local@* (global local name)
- *@domain (catch all for domain)
- *@* (catch all)

**Comment by mjl-** [comment]
Indeed that's what default domain does. And I agree it is more helpful than confusing. I think I added it just to save some typing when creating config files. For if you have lots of aliases in a domain.

But indeed it is clearer to just remove it, and always specify the address. I'm going to deprecate it, make sure the full domain is used when writing the file through the admin web pages, and remove it after a while.

The "*" would be tricky, it can also occur in an email address. There is currently no full catchall for localparts, only in combination with a separator character. Mox should either get an option for a catchall for a domain, or for specifying a regular expression.

**Comment by mjl-** [comment]
I think you're right about not needing regexps. I think having an empty localpart or domain to serve as wildcard will be better. It isn't valid as localpart. With a "*", folks may be tempted to use destination addresses like "user*@*.domain", hoping the "*" will match anything.

**Comment by mjl-** [comment]
A domain-catchall has been implemented, as destination address "@example.org". I didn't implement patterns "localpart@*" and "*@*" because they don't fit into the configuration model easily, and since setting up a domain is quite a bit of work (creating DNS records), making the admin also add another domain-catchall alias doesn't feel like too much to ask.

I hope to do another release within a week, this should be available then. Thanks for raising this issue. Feel free to reopen if needed.

**Comment by naturalethic** [comment]
Confirmed the catchalls are working great.  Thanks!
