### ISSUE TITLE
How to prolong the logged-in time in webmail?

### ISSUE THREAD

**Issue by ally9335** [mjl-/mox#202]
By default, it's around 2 weaks, right? How to prolong it?

**Comment by mjl-** [comment]
A session expires after 24 hours inactivity. It is extended each time it is used. The idea is that if you use the webmail every day, you won't have to login again.

The 24 hours is configured here:
https://github.com/mjl-/mox/blob/v0.0.11/store/session.go#L22

Which is being called through the webauth package:
https://github.com/mjl-/mox/blob/v0.0.11/webauth/webauth.go

By the way, the admin interface has sessions that aren't extended, and aren't persisted.

Perhaps this would already help you prevent getting expired sessions? Or perhaps we can find an other good (and still safe) heuristic for extending sessions.

**Comment by ally9335** [comment]
That's ok. I check it daily, but sometimes I may be on the road. 
Other than making it configurable, with the default value of 24h, how else could it be done?

**Comment by mjl-** [comment]
I've got the same, once in a while it turns out I didn't read email for a day (in the webmail). I see it as a good signal I may be relaxing a bit. (: 
We could make it a per-account setting (override of the default 24h) if it's really important enough. But I prefer to keep configurable options down. Perhaps it would help (with expectations, possibly letter user adjust behaviour) if we explain in the UI that sessions are automatically extended, only expiring after 24h inactivity.

**Comment by mjl-** [comment]
@ally9335 FYI, the commit just now causes the "session expired" message (shown above the login form when using a session fails) to show why that may have happened. Hopefully this helps other users discover what the behaviour is.
