### ISSUE TITLE
Receiving mail fails from one sender with acme certificate miss

### ISSUE THREAD

**Issue by RobSlgm** [mjl-/mox#206]
No mails are received from a sender (in the log below from 111.111.111.111) for the domain mail.example.org. 
Sending mails to the sender works without issues. Receiving from other sender (i.e. google, ms) works fine.

The mox server is running under example.com and handling example.org mails.

The log file seems to indicate an issue with the own certificate 'example.org'. This certificate doesn't exist (and should IMHO not exist), but valid certificate exist for mail.example.org, mts-sts.example.org and autoconfig.example.org. 

~~~
l=debug m="http request" pkg=http httpaccess= handler=mtasts method=get url=/.well-known/mta-sts.txt host=mta-sts.example.org duration="98.203µs" statuscode=200 proto=http/2.0 remoteaddr=111.111.111.111:50527 tlsinfo=tls1.3 useragent=SecurityGateway/1.0 referrr= size=63 cid=1914f99d691
l=info m="new connection" pkg=smtpserver remote=111.111.111.111:50528 local=49.13.208.167:25 submission=false tls=false listener=public cid=1914f99d692 delta="65.693µs"
l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=ehlo code=250 ecode= duration="37.65µs" cid=1914f99d692 delta=26.900377ms
l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=starttls code=220 ecode=2.0.0 duration="19.467µs" cid=1914f99d692 delta=27.973618ms
l=debug m="starting tls server handshake" pkg=smtpserver cid=1914f99d692 delta="120.085µs"
l=info m="getting cert from dir cache" err="acme/autocert: certificate cache miss" pkg=autotls name=example.org
l=debug m="dircache get result" err="acme/autocert: certificate cache miss" pkg=autotls name=example.org
l=debug m="autotls hostpolicy result" err="autotls: host not in allowlist: \"example.org\"" pkg=autotls host=example.org
l=debug m="requesting certificate" err="autotls: host not in allowlist: \"example.org\"" pkg=autotls host=example.org cid=1914f99d692
l=info m="connection closed" err="starttls handshake: tls: no certificates configured (io error)" pkg=smtpserver cid=1914f99d692 delta=28.733029ms
~~~

A check with https://internet.nl/mail/ of the sender shows a possible lack of STARTTLS support.

Some my questions are:
- How to read the log file entries correctly? 
- Can a "exception" be configured for an sender without STARTTLS support?

**Comment by mjl-** [comment]
Interesting issue. Below is a breakdown of the logs.

> l=debug m="http request" pkg=http httpaccess= handler=mtasts method=get url=/.well-known/mta-sts.txt host=mta-sts.example.org duration="98.203µs" statuscode=200 proto=http/2.0 remoteaddr=111.111.111.111:50527 tlsinfo=tls1.3 useragent=SecurityGateway/1.0 referrr= size=63 cid=1914f99d691

The remote smtp client (that is trying to make a delivery) is requesting an mta-sts policy. So it appears to implement MTA-STS for sending.

> l=info m="new connection" pkg=smtpserver remote=111.111.111.111:50528 local=49.13.208.167:25 submission=false tls=false listener=public cid=1914f99d692 delta="65.693µs"
> l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=ehlo code=250 ecode= duration="37.65µs" cid=1914f99d692 delta=26.900377ms
> l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=starttls code=220 ecode=2.0.0 duration="19.467µs" cid=1914f99d692 delta=27.973618ms

The remote smtp client has made an smtp connection and is trying to do starttls.

> l=debug m="starting tls server handshake" pkg=smtpserver cid=1914f99d692 delta="120.085µs"
> l=info m="getting cert from dir cache" err="acme/autocert: certificate cache miss" pkg=autotls name=example.org

The remote client is doing SNI with hostname "example.org".
This is surprising. Your IP is for a hostname mail.$domain, the MX record for $domain contains MX record mail.$domain, and the MTA-STS policy for $domain lists mail.$domain as valid MX. So that's all correct. Any smtp client making a TLS connection during delivery would normally try to verify the certificate for the MX hostname, mail.$domain in this case, and use it as SNI.

> l=debug m="dircache get result" err="acme/autocert: certificate cache miss" pkg=autotls name=example.org
> l=debug m="autotls hostpolicy result" err="autotls: host not in allowlist: \"example.org\"" pkg=autotls host=example.org
> l=debug m="requesting certificate" err="autotls: host not in allowlist: \"example.org\"" pkg=autotls host=example.org cid=1914f99d692
> l=info m="connection closed" err="starttls handshake: tls: no certificates configured (io error)" pkg=smtpserver cid=1914f99d692 delta=28.733029ms

Indeed, we don't have the requested certificate, and the TLS connection fails.
Mox keeps track of a list of hostnames to maintain TLS certificates for. The SNI name determines which to return. We can use ACME to fetch (initial or renew) TLS certificates. We don't want to bother the ACME provider (e.g. Let's Encrypt) with just any domain for which we get connection requests. For the domains I host, I typically setup up an HTTPS-redirect from $domain to www.$domain, so my mox instances do have TLS certs for bare domains. There's a chance this is a more common problem, but I just happened to have evaded it...

Do you know which software running at 111.111.111.111, that is trying to make the delivery? I don't think it's mox?

Two thoughts:

1. Mox currently is saying "I don't have a certificate for the hostname you requested, so we can't do TLS". This is probably unnecessarily strict. We could just continue with the certificate for the hostname. Then we'll leave it to the remote smtp client to decide whether the certificate is acceptable.
2. The remote smtp client seems to be doing MTA-STS. In that case, it MUST use the SNI name of the MX hostname according to the MTA-STS RFC. See https://www.xmox.nl/xr/dev/rfc/8461.html#L748. It seems to be in violation. It sounds a bit suspect that something doing MTA-STS (relatively recent) would use the wrong SNI name. There is a chance that it still won't be able to deliver even when we ignore the SNI name $domain and just serve up a certificate for mail.$domain due to new cert verification issues.

But let's implement thought 1 and see if it helps. Are you able to trigger a delivery attempt from said IP/mail server? Will help with testing.

> Can a "exception" be configured for an sender without STARTTLS support?

I don't think this is necessary, certainly not if we just use a certificate for the MX hostname instead of saying we don't have a certificate to use at all.

**Comment by mjl-** [comment]
Some more information about where these log lines from mox are coming from:

- https://github.com/mjl-/mox/blob/5678b03324864f01668f47c6a78e2d56efe456e5/autotls/autotls.go#L161-L202 is where we set up our ACME functionality. GetCertificate tries to get a cert for a requested ServerName (from SNI), often we'll have it ready to use, sometimes we need to fetch it through the ACME provider (eg Let's Encrypt). If there is no SNI, this acme manager won't return a cert. However, see the next point.
- When we set up our TLS config to be used in mox, we treat missing SNI as if our hostname was requested, see https://github.com/mjl-/mox/blob/5678b03324864f01668f47c6a78e2d56efe456e5/mox-/config.go#L716-L731.
- https://github.com/mjl-/mox/blob/5678b03324864f01668f47c6a78e2d56efe456e5/autotls/autotls.go#L317 is the code called to determine if we'll (try to) serve a TLS cert for a hostname. Essentially a lookup in a map of allowlisted hostnames.
- https://github.com/mjl-/mox/blob/5678b03324864f01668f47c6a78e2d56efe456e5/autotls/autotls.go#L241 is where the allowed host names are set, which is called when initializing the configuration (based on all domains being served), see https://github.com/mjl-/mox/blob/5678b03324864f01668f47c6a78e2d56efe456e5/mox-/config.go#L282.

I'm not so sure it's helpful to serve a cert for the hostname if there is no SNI match. It will be good to know why/how the sending smtp client decides to use that example.org in SNI.

**Comment by RobSlgm** [comment]
Wow, thanks for the awesome breakdown of the problem.

> Do you know which software running at 111.111.111.111, that is trying to make the delivery? I don't think it's mox?

No, its not mox. It's - based on header information - a product of https://mdaemon.com/ in a version 9.x. Most probably it's the MDaemons SecurityGateway for eMail.

> Are you able to trigger a delivery attempt from said IP/mail server? Will help with testing.

Not sure. The original mail was a booking confirmation triggered by a webpage, but the following mails from their support had the same issue. So I could ask the support nicely ...

I checked the logfiles for the last 2 months and it's the only occurrence with the $domain cert.
The logfiles contains a lot of hits with the IP of my mox host with the same pattern. After checking few samples of counterparties IP's I believe them to be SPAM. Some further hits are for foreign domains, again with no loss of "good" mails.

**Comment by mjl-** [comment]
Interesting. It doesn't seem easy to just run mdaemon locally, too bad.

I'm going to try changing only the SMTP port 25 TLS config to fallback to the cert of the hostname. I wasn't too eager about serving "wrong" certificates for eg submission/imap/http, but if we can keep it local to smtp delivery, there shouldn't be a downside, only potential improved interoperability.

**Comment by mjl-** [comment]
@RobSlgm The commit from just now makes the TLS config used  for the smtp server for incoming deliveries (not for submission, or imap etc) more lenient, falling back to a certificate of the (listener) hostname in case a remote smtp client tries starttls with an SNI hostname that isn't on the allowlist, instead of causing starttls to fail.
If you're in a position to trigger a delivery attempt from the mail server that was causing failures before to a mox instance running this commit, it will be interesting to see what happens next. (: The TLS connection should succeed, but the remote server (smtp client) can still decide it doesn't like our certificate.
For a binary for the commit, see https://www.xmox.nl/b/#62bd2f442731670a34c39926b064dfa34bb5d7ac.

**Comment by RobSlgm** [comment]
@mjl- Thank you!

Can confirm, that it works. I received all e-mails.

~~~
l=info m="new connection" pkg=smtpserver remote=111.111.111.111:61127 local=49.13.208.167:25 submission=false tls=false listener=public cid=1917ed4c3d0 delta="70.603µs"
l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=ehlo code=250 ecode= duration="95.007µs" cid=1917ed4c3d0 delta=26.912272ms
l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=starttls code=220 ecode=2.0.0 duration="20.047µs" cid=1917ed4c3d0 delta=27.913386ms
l=debug m="starting tls server handshake" pkg=smtpserver cid=1917ed4c3d0 delta="130.885µs"
l=info m="getting cert from dir cache" err="acme/autocert: certificate cache miss" pkg=autotls name=example.org
l=debug m="dircache get result" err="acme/autocert: certificate cache miss" pkg=autotls name=example.org
l=debug m="autotls hostpolicy result" err="autotls: host not in allowlist: \"example.org\"" pkg=autotls host=example.org
l=debug m="certificate for unknown hostname, using fallback hostname" pkg=autotls host=example.org cid=1917ed4c3d0
l=debug m="requesting certificate for fallback hostname" pkg=autotls host=mail.example.org cid=1917ed4c3d0
l=debug m="tls server handshake done" pkg=smtpserver tls=TLS1.3 ciphersuite=TLS_AES_128_GCM_SHA256 cid=1917ed4c3d0 delta=60.297984ms
l=debug m="smtp command result" pkg=smtpserver kind=smtp cmd=ehlo code=250 ecode= duration="59.001µs" cid=1917ed4c3d0 delta=334.715872ms
~~~

**Comment by mjl-** [comment]
Great, thanks for the detailed report and quick testing!
I'm still wondering about the SNI hostname used during delivery, why it's picking that one. Perhaps there's something special going on. For now I'll think of it as odd behaviour of the remote system. (:
