### ISSUE TITLE
Webmail: Invalid DATA renders "Rejects" folder unusable

### ISSUE THREAD

**Issue by wneessen** [mjl-/mox#219]
Hi,

first of all a big thanks for this great product. I've installed mox today on one of my servers and I'm really happy so far. As a Gopher myself I'm especially happy to run a Go mail server :)

While doing some testing on my new instance, I was trying to see what the server does when I deliver a non-standard mail via telnet. Basically all I did was providing "MAIL FROM", "RCPT TO" and "DATA" followed by non-compliant data. The good thing is, the mail was rejected, but as rejected mails are still delivered to the "Rejects" folder, I wanted to have a look. 

Unfortunately it seems the fact that I did not provide any kind of headers to the mail, renders the webmail view of the "Rejects" folder unusable. It will provide a popup showing a message that the mail has no valid headers and after that the error is displayed in the folder view. I would not be able to access any other rejected mails it seem.

Some screenshots of what I did and what I see below.

My telnet session:
![Screenshot_Montag, 30  September 2024_17h51m27s_0003](https://github.com/user-attachments/assets/ae61620c-bf4a-432e-a682-bf629678a5e9)

The webmail view:
![Screenshot_Montag, 30  September 2024_17h50m59s_0002](https://github.com/user-attachments/assets/0367e0e2-fa5c-4356-9858-43b93467a71a)

Excuse the XSS data in the screenshot. Once I realized that the webview is trying to interpret the broken mail, I checked if I could XSS out of it. But luckily that seems not successful (at least not at this simple test I did).

In the end, it's not a big deal, since I can still download the Rejects folder via IMAP, but I wanted to make sure that this gets reported, since I don't think this is an expected behaviour.

**Comment by mjl-** [comment]
Yes, thanks for reporting, this definitely needs to be fixed. I've seen an error message when loading an individual bad message, but this is worse, preventing an entire mailbox from being listed.

Nice test case with the xss attempt. (: The webmail client is all javascript, no html from the backend is used verbatim. The html view is protected by CSP headers, to prevent js from running and external resources loaded. If you're into that sort of thing, could be nice to see if there are any problems/oversights with how that's done.

**Comment by mjl-** [comment]
The commit just now should fix loading a mailbox that has an "initial" message that cannot be parsed. The mox backend normally doesn't fully parse each message that it's returning in a mailbox view. But it does parse the "initial" message, that's opened by default upon mailbox load. If that parsing failed, loading the view would fail entirely. With this fix, we log & ignore such malformed initial message, causing the frontend to not immediately show an initial message.

It will probably be better to signal the parsing error explicitly to the webmail frontend, so it can show a nice "malformed message" line where we would otherwise show the message contents. Now it feels a bit too much like a backend error. But it would require larger changes, I think this is ok for now.

**Comment by mjl-** [comment]
Seems fixed, and part of v0.0.12, so closing the issue. Feel free to reopen if problems persist.
