### ISSUE TITLE
Web interface screenshots or demo

### ISSUE THREAD

**Issue by immanuelfodor** [mjl-/mox#26]
It would be great to add some screenshots of the web interface to the readme or provide an online demo account to help adoption and lower the barrier to evaluate the project. 

Possible user scenario: _"I've heard about this shiny new email project, and I might switch to it from my existing solution, but does it worth it?"_

**Comment by mjl-** [comment]
Thanks, good idea, I'll some soon.

**Comment by mjl-** [comment]
I also want to make a video that just shows setting up mox on a new machine for a new domain. I think that will give potential new users a good idea of what they are getting into. Will leave this issue open until then.

**Comment by moatorres** [comment]
@mjl- , I was wondering if you would welcome contributions to the existing web interface? I'd be happy to build one with React or add bits of CSS to it.

**Comment by mjl-** [comment]
hi @moatorres, i would be more interested in adding missing functionality in the web interfaces (e.g. making more of the domains.conf settings configurable through the admin web interface). also, the js (in web/admin.html and web/accounts.html) has some todo's about updating part of the views with new data (instead of reloading the whole page), that's possibly where the idea to use a library like react comes from. but i prefer to implement those in the style of the pure js approach we currently have, i think that approach can last for quite a while longer. using popular frontend libraries makes the web interfaces whole big projects on their own, and requires a lot of ever churning frontend tooling...

as for css changes: a few styling tweaks would be fine, especially the "dns check" page looks a bit off. but otherwise i'm quite happy with the basic look: no distractions, and few things to have to worry about creating the pages.

i do have another idea for the web interfaces, especially the pages that change settings in domains.conf: change them so they are essentially a guided editor for the configuration file. the configuration file is defined by a struct, with fields that are just types like structs, maps/objects, lists, strings and other base types. instead of writing custom ui's for changing those settings (the current approach), it would perhaps be good enough to (generically) show (parts of) the config file and provide buttons for adding/removing items from a list or map, and selecting one of a fixed set of options. perhaps sometimes with a little extra code to guide users in the right direction. the config file definition has annotations for documentation and whether fields are optional, so those can help. this may provide the discoverability and easy of use of a web interface, but keep the gap between web interface and config file small, making it easy to switch between the two. but this idea is a project on its own...

**Comment by mjl-** [comment]
Earlier this week I replaced the "website-placeholder" at https://www.xmox.nl with an actual website. It even has a first (somewhat awkward) video, with more to come (I hope to get better at it).

I'll close this issue for now, feel free to reopen. Feedback also welcome, that also works on closed issues, I'll get a notification by email.
