### ISSUE TITLE
Mox not able to send mail to Gmail

### ISSUE THREAD

**Issue by dmikushin** [mjl-/mox#36]
I've been testing Mox installation on the host system (without Docker). Receiving mail works well, sending mail does not work. Apparently, Mox is unable to connect to Gmail server, what could be the reason? I've also asked Mox to send mail to itself - also no delivery. Please find the Gmail sending errors log below.

```
Jun 12 00:05:21 xxxxxxxxxxx mox[426904]: l=debug m="queue deliverhost result" cid=188ace60a0d from=team@xxxxxxxxxxx recipient=xxxxxxxxx@gmail.com attempts=3 msgid=2 cid=188ace60a08 pkg=queue host=alt3.gmail-smtp-in.l.google.com attempt=4 tlsmode=strict permanent=false badtls=false secodeopt= errmsg="dialing smtp server: dial tcp [2404:6800:4008:c13::1b]:25: i/o timeout" ok=false duration=30.01200778s
Jun 12 00:05:21 xxxxxxxxxxx mox[426904]: l=info m="delivering to remote" from=team@xxxxxxxxxxx recipient=xxxxxxxxx@gmail.com attempts=3 msgid=2 cid=188ace60a08 pkg=queue remote=alt4.gmail-smtp-in.l.google.com queuecid=1686527937032
Jun 12 00:05:21 xxxxxxxxxxx mox[426904]: l=debug m="dns lookup result" cid=188ace60a0e pkg=dns pkg=queue type=ipaddr host=alt4.gmail-smtp-in.l.google.com. resp="[ip=173.194.202.27;ip=2607:f8b0:400e:c00::1a]" duration=72.877307ms
Jun 12 00:05:21 xxxxxxxxxxx mox[426904]: l=debug m="dialing remote smtp" cid=188ace60a0e from=team@xxxxxxxxxxx recipient=xxxxxxxxx@gmail.com attempts=3 msgid=2 cid=188ace60a08 pkg=queue addr=173.194.202.27:25
Jun 12 00:05:36 xxxxxxxxxxx mox[426904]: l=debug m="connection attempt for smtp delivery" err="dial tcp 10.0.0.67:0->173.194.202.27:25: i/o timeout" cid=188ace60a0e from=team@xxxxxxxxxxx recipient=xxxxxxxxx@gmail.com attempts=3 msgid=2 cid=188ace60a08 pkg=queue host=alt4.gmail-smtp-in.l.google.com addr=173.194.202.27:25 laddr=10.0.0.67:0
Jun 12 00:05:36 xxxxxxxxxxx mox[426904]: l=debug m="dialing remote smtp" cid=188ace60a0e from=team@xxxxxxxxxxx recipient=xxxxxxxxx@gmail.com attempts=3 msgid=2 cid=188ace60a08 pkg=queue addr=[2607:f8b0:400e:c00::1a]:25
Jun 12 00:05:51 xxxxxxxxxxx mox[426904]: l=debug m="connection attempt for smtp delivery" err="dial tcp [2607:f8b0:400e:c00::1a]:25: i/o timeout" cid=188ace60a0e from=team@xxxxxxxxxxx recipient=xxxxxxxxx@gmail.com attempts=3 msgid=2 cid=188ace60a08 pkg=queue host=alt4.gmail-smtp-in.l.google.com addr=[2607:f8b0:400e:c00::1a]:25 laddr=
Jun 12 00:05:51 xxxxxxxxxxx mox[426904]: l=debug m="connecting to remote smtp" err="dial tcp [2607:f8b0:400e:c00::1a]:25: i/o timeout" cid=188ace60a0e from=team@xxxxxxxxxxx recipient=xxxxxxxxx@gmail.com attempts=3 msgid=2 cid=188ace60a08 pkg=queue host=alt4.gmail-smtp-in.l.google.com
Jun 12 00:05:51 xxxxxxxxxxx mox[426904]: l=debug m="queue deliverhost result" cid=188ace60a0e from=team@xxxxxxxxxxx recipient=xxxxxxxxx@gmail.com attempts=3 msgid=2 cid=188ace60a08 pkg=queue host=alt4.gmail-smtp-in.l.google.com attempt=4 tlsmode=strict permanent=false badtls=false secodeopt= errmsg="dialing smtp server: dial tcp [2607:f8b0:400e:c00::1a]:25: i/o timeout" ok=false duration=30.000330764s
Jun 12 00:05:51 xxxxxxxxxxx mox[426904]: l=error m="temporary failure delivering from queue" err="dialing smtp server: dial tcp [2607:f8b0:400e:c00::1a]:25: i/o timeout" from=team@xxxxxxxxxxx recipient=xxxxxxxxx@gmail.com attempts=3 msgid=2 cid=188ace60a08 pkg=queue backoff=1h0m24s nextattempt="2023-06-12 01:03:44.952964679 +0000 UTC m=+3887.941291992"
```

**Comment by mjl-** [comment]
The error message `dialing smtp server: dial tcp [2404:6800:4008:c13::1b]:25: i/o timeout` indicates no TCP connection could be made to the gmail smtp server. I suspect the outgoing traffic is being blocked by your hosting provider. Hosting providers often do this for new VPS'es to combat spam (spammers would get start a new VPS and start spamming right away). These hosting providers often automatically open up the port after an initial cooldown period (e.g. 12 or 24 hours), or you have to ask them in a support ticket. Some hosting providers (typically the cheap ones that don't want to spend resources on maintaining email reputations for their networks) don't let you send email at all.

Could you try to connect to the gmail smtp server from the command line? For example:

```
$ nc -v 2404:6800:4008:c13::1b 25
Connection to 2404:6800:4008:c13::1b 25 port [tcp/smtp] succeeded!
220 mx.google.com ESMTP x6-20020a17090aca0600b00258cb09c4a8si8361757pjt.71 - gsmtp
```

I suspect you'll get a similar timeout message. It will probably be the same for sending to other mail servers.

**Comment by dmikushin** [comment]
Hi @mjl- , thank you for this information! Indeed, I have timeout when running `nc -v 2404:6800:4008:c13::1b 25` on Oracle cloud instance only, the same query succeeds on my local machine. This is interesting, because my instance is 2-years old.

Could I tunnel Mox outgoing connections to some other machine, where I know that SMTP is not blocked?

**Comment by mjl-** [comment]
Mox currently cannot make outgoing connections through a SOCKS proxy, but I'll try to add it this week. Same for sending through an external SMTP account.

**Comment by mjl-** [comment]
hi @dmikushin, i added support for using a SOCKS transport when delivering email from the queue. could you give it a try if you still need it?

You would need to configure a transport in mox.conf, called "socks" in the following example:

```
Transports:
        socks:
                Socks:
                        Address: localhost:1080
                        RemoteIPs:
                                - ... ip that socks proxy will connect from...
                                - ...
                        RemoteHostname: ... hostname for remote IPs ...
```

And you would have to create a "route" so this transport is used (instead of the default direct delivery without socks). You could add a global route in domains.conf (you could also configure them per account or per domain). For a global route in domains.conf, add:

```
Routes:
        -
                Transport: socks
```

You could also configure an existing submission account to send emails. To send through an SMTP service of a cloud provider. I've tried it with AWS SES. It wasn't smooth (they only support old SASL PLAIN auth, not less old SCRAM-SHA or CRAM-MD5, they don't support smtputf8, and they choke on "duplicate" dkim-signature headers), but it worked after jumping the hoops. As a side-effect the smtpclient improved, and using mox as the system "sendmail" can now also use the modern authentication mechanisms.

**Comment by dmikushin** [comment]
Hi @mjl- , yes I need it. 

Hm, so in addition to normal SOCKS5 options, I will need to tell IP and hostname of machine where Mox is running, right?

**Comment by mjl-** [comment]
The IP and Hostname should be of the machine running the SOCKS proxy. Mox wants to know from which IP/hostname the connection appears to be coming from viewed from the destination MX server. The hostname is used in the SMTP EHLO command. The IP is checked in any DNS blocklist that is configured, and mox checks if it appears in SPF records for domains.

**Comment by dmikushin** [comment]
Ohh I see. But in my case, this is going to be what - a local network address? Or do I need to put there an address reported by myip service? It could be dynamic...

**Comment by mjl-** [comment]
It should be a public IP address and host name. But it needs to be one with reverse DNS properly configured, and the IP shouldn't in public blocklists. A dialup or your home DSL/cable/fibre internet connection probably won't work, because plenty of mail servers won't accept email from such servers. It also won't be very convenient to use many different IP's, because you'll have to update the domain SPF record each time you change an IP.

So when mox tries to deliver a message from the queue, it is looks up the MX DNS records for the domain of the "to" address. It connects to the first MX host on port 25 (smtp). Normally the connection is coming directly from the machine where mox runs, so from an IP configured on that machine. But socks, the connection will appear to come from your socks proxy. So any requirements that are normally on the IP of the mox machine, are now placed on the machine running the SOCKS proxy. Hope this clarifies it. I thought you had a separate VPS somewhere else to run the SOCKS proxy on.

**Comment by mjl-** [comment]
hi @dmikushin, just wondering if you found a solution for sending mail...

**Comment by mjl-** [comment]
Closing this for now, feel free to reopen to continue discussion.
