### ISSUE TITLE
Config parser seems to not truncate comments?

### ISSUE THREAD

**Issue by kikoreis** [mjl-/mox#56]
I added a comment at the end of a line in my config file like this:

```
              IPs:
                        - X.X.X.X # BAD
```
Running mox then fails:
```
l=fatal m="http: listen" err="listen tcp: lookup X.X.X.X # BAD: no such host" pkg=http addr="X.X.X.X # BAD:8010"
```
I didn't look at the config parsing code but shouldn't it be doing the equivalent of a `foo.split("#")[0]` for each line?

Note this leads to some weird results if you use it in places like:
```
DataDir: ../data # FOO
```
because it leads to things like:
```
drwxr-s--- 6 mox  root     4096 Aug 29 01:52 'data # FOO'
```
This suggests you might want to also sanitize inputs in the filesystem handling code because that in some cases can lead to weird exploits being possible/easier.

**Comment by mjl-** [comment]
Hi @kikoreis, good points. The format is a custom format called sconf. Not stripping "#" at the end of lines is indeedlikely surprising for people used to editing config files. Sconf is intentionally very basic, and so is the string parsing. E.g. there is no way to have a multiline string, there is no escaping mechanism. And that's why "#" is also not treated specially.

I can't easily add "#"-as-comment handling to sconf, perhaps in a future update. But I'll add a comment to the top of the config files explaining some peculiarities of the format, that will hopefully prevent some problems.

**Comment by mjl-** [comment]
I think this is finished. If you have other changes in mind, feel free to reopen.
